spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here}
  access-token:
    expiration: 900000 # 15 minutes in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.example.iam: DEBUG 