spring:
  application:
    name: iam-service

  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 15112002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

app:
  jwt:
    secret: 4b472c95dd9b5a76d664d094b55d47488cbd8d863e70979d22db2bba9d64b5a1aeb818f08b3827028c7ec48f78a1f53b3472469919bbbe4c933e9a942d75c3b12ea3c8dc6c6b0db89e3f3b058c4e46103158be6fa14e7622b2dd2e3f62b78f1619a7db8fcc1b7cf1cf0cc942cf889a0ea685ce409d09900f425f43631c350bff7a53aef695df06973f7b08d9afc99f66b9b71f8f0456e6633733fb8b47e94e3ce2db92a3b9064db0e6c635bd80220afce4083df8bde5119ea4f7a8193af2536055b12a60a8d896bfcb4cb64b8cfbb7f4f86d844055c3adcd9ca6f65701d87b16959fd71206ecf26b34b56d29523de04f578e0e812bc7aa85313bb18762f7222a
    access-token:
      expiration: 3600000
    refresh-token:
      expiration: 604800000

logging:
  level:
    root: INFO
    com.example.iam: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.springframework.orm: ERROR
    org.springframework.transaction: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"