spring:
  application:
    name: ${SPRING_APPLICATION_NAME:iam-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/iam_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:15112002}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}

springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:true}
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:true}
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

app:
  jwt:
    # secret: [REMOVED for security]
    key:
      private: ${APP_JWT_KEY_PRIVATE:classpath:certs/private.pem}
      public: ${APP_JWT_KEY_PUBLIC:classpath:certs/public.pem}
    access-token:
      expiration: ${APP_JWT_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token:
      expiration: ${APP_JWT_REFRESH_TOKEN_EXPIRATION:604800000}

  super-admin:
    username: ${APP_SUPER_ADMIN_USERNAME:superadmin}
    password: ${APP_SUPER_ADMIN_PASSWORD:admin}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.example.iam: ${LOGGING_LEVEL_COM_EXAMPLE_IAM:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_HIBERNATE_SQL:OFF}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_HIBERNATE_BINDER:OFF}
    org.springframework.security: ${LOGGING_LEVEL_SPRING_SECURITY:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRING_WEB:INFO}
    org.hibernate: ${LOGGING_LEVEL_HIBERNATE:ERROR}
    org.springframework.orm: ${LOGGING_LEVEL_SPRING_ORM:ERROR}
    org.springframework.transaction: ${LOGGING_LEVEL_SPRING_TRANSACTION:ERROR}
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:"%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"}
