spring:
  application:
    name: iam-service

  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db
    username: postgres
    password: 15112002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

app:
  jwt:
    # secret: [REMOVED for security]
    key:
      private: classpath:certs/private.pem
      public: classpath:certs/public.pem
    access-token:
      expiration: 3600000 # 1 hour
    refresh-token:
      expiration: 604800000

  super-admin:
    username: superadmin # Default superadmin username
    password: admin # Default superadmin password. CHANGE THIS IN PRODUCTION.

logging:
  level:
    root: INFO
    com.example.iam: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.springframework.orm: ERROR
    org.springframework.transaction: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
